# This is a boilerplate parameters config generated for pipeline 'preprocessing'
# using Kedro 0.19.1.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.1/configuration/parameters.html
Parameters_training:
  batch_size: 256
  num_workers: 2
Parameters_testing:
  batch_size: 256
  num_workers: 2
Parameters_adversarial_generation:
  batch_size: 256
  num_workers: 2