Data_information: 
  name: ${globals:Dataset_information.name}
  mean: ${globals:Dataset_information.mean}
  std: ${globals:Dataset_information.std}
  input_shape: ${globals:Dataset_information.input_shape}
  classes: ${globals:Dataset_information.classes}