Data_information: 
  name: ${globals:Dataset_information.name}
  root: ${globals:Dataset_information.root}
  mean: ${globals:Dataset_information.mean}
  std: ${globals:Dataset_information.std}
  input_shape: ${globals:Dataset_information.input_shape}
  classes: ${globals:Dataset_information.classes}
  Top_k: ${globals:Dataset_information.Top_k}
  Classes_names: ${globals:Dataset_information.Classes_names}